branch-defaults:
  develop:
    environment: Tellus-env
environment-defaults:
  Tellus-env:
    branch: null
    repository: null
global:
  application_name: tellus
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:ap-northeast-2::platform/Node.js running
    on 64bit Amazon Linux/4.5.1
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
